### PR TITLE
key_io.cpp: apply clang-format

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
```
cd src
clang-format -i key_io.cpp --lines=78:127
```

NOTE: the formatting is only applied to your change.
keep the formatting to the scope of your commits.

You can get the --lines=###:### value from a git diff

**Comment by RandyMcMillan** [comment]
In cases like this: leave the clang-format in its own commit for easier review.
You will likely be asked to squash the commit after review, etc...

you can also merge this commit on to this branch

after review:

pull then squash via interactive rebase
fixup commit message

example:
```
git rebase -i 0f8c95dccd120ad5fd371f81025137b855796f13
```





rebase-example

**Comment by RandyMcMillan** [comment]
Screen Shot 2023-05-27 at 7 46 04 AM

**Comment by portlandhodl** [comment]
Thank you very much! 

Yeah most of the time when I don't squash, it is requested quickly on the PR

**Comment by portlandhodl** [comment]
BTW I am going to try this again, I hard reset to the previous commit. This time I am going to rebase it in using the command line instead of Github.

Edit: Resolved 

image

**Pull request merged**
